language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
    packages:
      - libelf-dev
      - linux-headers-4.4.0-184-generic

script:
 - make -C driver check
 - KERNEL_VERSION=4.4.0-184-generic make -C driver
